[package]
name = "initia-vesting"
version = "0.0.0"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "main" }

[addresses]
std = "0x1"
vesting = "_"

[dev-addresses]
vesting = "0x2"
